name: DracoPlugin
main: me.jonasxpx.meuplugin2.MeuPlugin
version: 1.2
commands:
    worldset:
    warp:
    delwarp:
    setwarp:
    listwarps:
       aliases: [warps,warplist]
    home:
       aliases: [homes]
    listhomes:
       aliases: [homelist, homeslist]
    minerar:
       aliases: [mina]
    sethome: